services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mydatabase
      - PHP_INI_SCAN_DIR=:/usr/local/etc/php/custom.d
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"  # Changed host port from 3306 to 3307
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
